application: cssi-final-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /../css/home\.css
  static_files: ../css/home.css
  upload: ../css/home\.css

- url: /allscript\.js
  static_files: allscript.js
  upload: allscript\.js

- url: /indexcover\.jpg
  static_files: indexcover.jpg
  upload: indexcover\.jpg

- url: /../html/title\.html
  static_files: ../html/title.html
  upload: ../html/title\.html

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
