application: cssi-final-project
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:


- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /css
  static_dir: css

- url: /photos
  static_dir: photos

- url: /javascript
  static_dir: javascript


# - url: /../css/*\.css
#   static_files: ../css/*.css
#   upload: ../css/*\.css
#
# - url: /allscript\.js
#   static_files: allscript.js
#   upload: allscript\.js
#
# - url: /../photos/indexcover\.jpg
#   static_files: ../photos/indexcover.jpg
#   upload: ../photos/indexcover\.jpg
#
# - url: /../html/title\.html
#   static_files: ../html/title.html
#   upload: ../html/title\.html
#
# - url: /.*
#   static_dir: css
#   script: main.app

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
