'use strict';(function(){var a=DOMParser.prototype,b=a.parseFromString;try{var c=new DOMParser;if(c.parseFromString("","text/html")&&c.parseFromString("","image/svg+xml"))return}catch(d){}a.parseFromString=function(a,c){if(/^\s*(?:text\/html|application\/xhtml\+xml|image\/svg\+xml)\s*(?:;|$)/i.test(c)){var d=d.implementation.createHTMLDocument("");d.documentElement.innerHTML=a;return d}return b.apply(this,arguments)}})();"classList"in document.documentElement||!Object.defineProperty||"undefined"===typeof Element||Object.defineProperty(Element.prototype,"classList",{get:function(){function a(){return"undefined"!==typeof SVGAnimatedString&&c.className instanceof SVGAnimatedString?c.className.animVal:c.className}function b(b){return function(d){var g=a().split(/\s+/),h=g.indexOf(d);b(g,h,d);d=g.join(" ");"undefined"!==typeof SVGAnimatedString&&c.className instanceof SVGAnimatedString?c.className.baseVal=d:c.className=
d}}var c=this,d={add:b(function(a,b,c){~b||a.push(c)}),remove:b(function(a,b){~b&&a.splice(b,1)}),toggle:b(function(a,b,c){~b?a.splice(b,1):a.push(c)}),contains:function(b){return!!~a().split(/\s+/).indexOf(b)},item:function(b){return a().split(/\s+/)[b]||null}};Object.defineProperty(d,"length",{get:function(){return a().split(/\s+/).length}});return d}});"matches"in document.documentElement||!Object.defineProperty||"undefined"===typeof Element||(Element.prototype.matches=Element.prototype.msMatchesSelector||Element.prototype.webkitMatchesSelector||Element.prototype.mozMatchesSelector);if(!(document.documentElement.dataset||Object.getOwnPropertyDescriptor(Element.prototype,"dataset")&&Object.getOwnPropertyDescriptor(Element.prototype,"dataset").get)){var propDescriptor={enumerable:!0,get:function(){var a,b,c,d,e,f=this.attributes,g=f.length,h=function(a){return a.charAt(1).toUpperCase()},k=function(){return this},l=function(a,b){return"undefined"!==typeof b?this.setAttribute(a,b):this.removeAttribute(a)};try{({}).__defineGetter__("test",function(){}),b={}}catch(m){b=document.createElement("div")}for(a=
0;a<g;a++)if((d=f[a])&&d.name&&/^data-\w[\w\-]*$/.test(d.name)){c=d.value;d=d.name;e=d.substr(5).replace(/-./g,h);try{Object.defineProperty(b,e,{enumerable:this.enumerable,get:k.bind(c||""),set:l.bind(this,d)})}catch(n){b[e]=c}}return b}};try{Object.defineProperty(Element.prototype,"dataset",propDescriptor)}catch(e$$4){propDescriptor.enumerable=!1,Object.defineProperty(Element.prototype,"dataset",propDescriptor)}};"selectedOptions"in HTMLSelectElement.prototype||Object.defineProperty(HTMLSelectElement.prototype,"selectedOptions",{get:function(){try{return document.querySelector(":checked"),function(){return this.querySelectorAll(":checked")}}catch(a){return function(){if(!this.multiple)return 0<=this.selectedIndex?[this.options[this.selectedIndex]]:[];for(var a=0,c=[];a<this.options.length;a++)this.options[a].selected&&c.push(this.options[a]);return c}}}()});!1 in Number&&(Number.isInteger=function(a){return Math.round(a)===a});"function"!=typeof String.prototype&&(String.prototype.repeat=function(a){if(null==this)throw new TypeError;var b=String(this);a=a?Number(a):0;a!=a&&(a=0);if(0>a||Infinity==a)throw new RangeError;for(var c="";a;)1==a%2&&(c+=b),1<a&&(b+=b),a>>=1;return c});"onmousewheel"in document.createElement("div")&&!("onwheel"in document.createElement("div")||document.implementation.hasFeature("Events.wheel","3.0"))&&(window.WheelEvent={DOM_DELTA_PIXEL:0,DOM_DELTA_LINE:1,DOM_DELTA_PAGE:2,fromEvent:function(a){return Object.create(a,{deltaX:{value:"wheelDeltaX"in a?-.025*a.wheelDeltaX:0,writable:!1},deltaY:{value:-.025*a.wheelDelta,writable:!1},deltaZ:{value:0,writable:!1},deltaMode:{value:"MozMousePixelScroll"==a.type?0:1,writable:!1},type:{value:"wheel",writable:!1},
preventDefault:{value:function(){Object.getPrototypeOf(this).preventDefault()}}})},__polyfill_wheel_callback_count:0},[Node.prototype,Window.prototype].forEach(function(a){var b=a.addEventListener,c=a.removeEventListener;a.addEventListener=function(a,c,f){if("wheel"==a){a="mousewheel";var g=c;c=g.__polyfill_wheel_callback_id=g.__polyfill_wheel_callback_id||"callback"+WheelEvent.__polyfill_wheel_callback_count++;c=(this.__polyfill_wheel_callbacks=this.__polyfill_wheel_callbacks||{})[c]=function(a){a=
WheelEvent.fromEvent(a);if("function"==typeof g)return g(a);if(g.handleEvent)return g.handleEvent.call(g,a)}}return b.call(this,a,c,f)};a.removeEventListener=function(a,b,f){if("wheel"==a){a="mousewheel";var g=b.__polyfill_wheel_callback_id,h=this.__polyfill_wheel_callbacks[g];h&&(delete this.__polyfill_wheel_callbacks[g],b=h)}return c.call(this,a,b,f)}}));"cancelAnimationFrame"in window||(window.cancelAnimationFrame="webkitCancelAnimationFrame"in window?window.webkitCancelAnimationFrame:function(a){window.clearTimeout(a)});"devicePixelRatio"in window||(window.devicePixelRatio=1);"requestAnimationFrame"in window||("webkitRequestAnimationFrame"in window?window.requestAnimationFrame=window.webkitRequestAnimationFrame:function(){var a=0;window.requestAnimationFrame=function(b,c){var d=Date.now(),e=Math.max(0,16-(d-a));a=d+e;return window.setTimeout(function(){b(d+e)},e)}}());"scrollMaxX"in window||Object.defineProperty(window,"scrollMaxX",{get:function(){var a=window.document.documentElement;return a.scrollWidth-a.clientWidth}});"scrollMaxY"in window||Object.defineProperty(window,"scrollMaxY",{get:function(){var a=window.document.documentElement;return a.scrollHeight-a.clientHeight}});"scrollX"in window||Object.defineProperty(window,"scrollX",{get:function(){return window.pageXOffset},set:function(a){window.pageXOffset=a}});"scrollY"in window||Object.defineProperty(window,"scrollY",{get:function(){return window.pageYOffset},set:function(a){window.pageYOffset=a}});function App(a){this._element=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._clickHandlerBound=this._clickHandler.bind(this);this._submitHandlerBound=this._submitHandler.bind(this);this._loadHandlerBound=this._loadHandler.bind(this);this._ideaClickHandlerBound=this._ideaClickHandler.bind(this);var b=a.getElementsByTagName("iframe");this._decorations=Array(b.length);for(var c=0,d=b.length;c<d;c++)this._decorations[c]=new AppDecorationIFrame(b[c]);(b=a.getElementsByClassName("app_video")).length&&
(this._videoDialog=new AppVideoDialog(b[0]),this._document.addEventListener("click",this._clickHandlerBound,!1));if((b=a.getElementsByClassName("app_feedback-ideas-form")).length){this._form=b[0];this._form.addEventListener("submit",this._submitHandlerBound,!1);this._potentialsSubmitters=[];for(var e,f=0,g=this._form.elements,h=g.length;f<h;f++)if(c=g[f],d=c.nodeName,e=c.type,"BUTTON"==d&&"submit"==e||"INPUT"==d&&"reset"==e||"INPUT"==d&&"submit"==e||"INPUT"==d&&"image"==e)c.addEventListener("click",
this._ideaClickHandlerBound,!1),this._potentialsSubmitters.push(c)}c=[];d=["app_summary","app_video-link-container","app_screenshot","app_feedback","app_feedback-ideas-list"];e=0;for(f=d.length;e<f;e++)(b=a.getElementsByClassName(d[e])).length&&c.push(b[0]);c=c.concat(Array.prototype.slice.call(this._element.getElementsByClassName("app_description")));this._scrollAnimator=new ScrollAnimator(this._window,c);this._animateDecorationTimeoutID=setTimeout(this._animateDecorations.bind(this),700)}
App.prototype._window=null;App.prototype._document=null;App.prototype._element=null;App.prototype._decorations=null;App.prototype._videoDialog=null;App.prototype._scrollAnimator=null;App.prototype._animateDecorationTimeoutID=0;App.prototype._clickHandlerBound=null;App.prototype._loadHandlerBound=null;App.prototype._ideaClickHandlerBound=null;App.prototype._form=null;App.prototype._sender=null;App.prototype._formEncoder=null;App.prototype._potentialsSubmitters=null;App.prototype._submitter=null;
App.prototype._animateDecorations=function(){for(var a=0,b=this._decorations.length;a<b;a++)this._decorations[a].state="target"};
App.prototype._clickHandler=function(a){if(!a.defaultPrevented)for(var b=a.target,c=this._window.location;b;){if("A"==b.nodeName){var d=b.hash.substr(1);b.protocol==c.protocol&&b.hostname==c.hostname&&(b.port==c.port||80==b.port&&""==c.port)&&b.pathname==c.pathname&&b.search==c.search&&this._document.getElementById(d)==this._videoDialog.element&&(a.preventDefault(),this._videoDialog.open());break}b=b.parentElement}};
App.prototype._submit=function(){if(this._submitter){this._sender?this._sender.abort():(this._sender=new XMLHttpRequest,this._sender.addEventListener("load",this._loadHandlerBound,!1),this._formEncoder=new FormDataEncoder);this._sender.open(this._form.method,this._form.dataset.action);this._sender.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");var a=FormDataReader.getEntries(this._form);a.push(new FormDataEntry(this._submitter.name,this._submitter.value,this._submitter.type));
this._formEncoder.encode(a);this._sender.send(this._formEncoder.result)}};App.prototype._ideaClickHandler=function(a){this._submitter=a.currentTarget};App.prototype._submitHandler=function(a){this._submit();a.preventDefault()};App.prototype._loadHandler=function(a){a=JSON.parse(this._sender.responseText);this._form.elements.nonce.value=a.nonce;1==a.code&&(this._submitter.disabled=!0,this._submitter=null)};
App.prototype.clear=function(){for(var a=0,b=this._decorations.length;a<b;a++)this._decorations[a].clear();this._videoDialog&&this._videoDialog.clear();this._document.removeEventListener("click",this._clickHandlerBound,!1);if(this._form)for(this._form.removeEventListener("submit",this._submitHandlerBound,!1),a=0,b=this._potentialsSubmitters.length;a<b;a++)this._potentialsSubmitters[a].removeEventListener("click",this._ideaClickHandlerBound,!1);this._sender&&(this._sender.removeEventListener("load",
this._loadHandlerBound,!1),this._sender.abort());clearTimeout(this._animateDecorationTimeoutID);this._scrollAnimator.clear();return!0};function AppDecorationIFrame(a){this._element=a;this._contentWindow=this._element.contentWindow;this._messageHandlerBound=this._messageHandler.bind(this);this._element.ownerDocument.defaultView.addEventListener("message",this._messageHandlerBound,!1);this._channelOpened||this._contentWindow.postMessage("open","*")}AppDecorationIFrame.prototype._element=null;AppDecorationIFrame.prototype._contentWindow=null;AppDecorationIFrame.prototype._channelOpened=!1;AppDecorationIFrame.prototype._state=null;
AppDecorationIFrame.prototype._messageHandlerBound=null;Object.defineProperty(AppDecorationIFrame.prototype,"state",{get:function(){return this._state},set:function(a){this._state=a;this._channelOpened&&this._contentWindow.postMessage("target"==this._state?"target":"untarget","*")}});
AppDecorationIFrame.prototype._messageHandler=function(a){a.source==this._contentWindow&&("wait"!=a.data||this._channelOpened?"ready"==a.data&&(this._channelOpened=!0,this._contentWindow.postMessage("target"==this._state?"target":"untarget","*")):this._contentWindow.postMessage("open","*"))};AppDecorationIFrame.prototype.clear=function(){this._element.ownerDocument.defaultView.removeEventListener("message",this._messageHandlerBound,!1);return!0};function Apps(a){this._element=a;this._mouseHandlerBound=this._mouseHandler.bind(this);var b,c,d,e=0;this._decoratedAppElements=[];this._decorations=[];if(a=(b=a.getElementsByClassName("apps_app")).length)for(var f=0;f<a;f++)if(c=b[f],d=c.getElementsByClassName("apps_app-decoration")[0])c.addEventListener("mouseenter",this._mouseHandlerBound,!1),c.addEventListener("mouseleave",this._mouseHandlerBound,!1),this._decoratedAppElements[e]=c,this._decorations[e]=new AppDecorationIFrame(d),e++}
Apps.prototype._element=null;Apps.prototype._decoratedAppElements=null;Apps.prototype._mouseHandlerBound=null;Apps.prototype._decorations=null;Apps.prototype._mouseHandler=function(a){var b=this._decoratedAppElements.indexOf(a.currentTarget);0<=b&&(this._decorations[b].state="mouseenter"==a.type?"target":"untarget")};
Apps.prototype.clear=function(){for(var a=0,b=this._decoratedAppElements.length;a<b;a++){var c=this._decoratedAppElements[a];c.removeEventListener("mouseenter",this._mouseHandlerBound,!1);c.removeEventListener("mouseleave",this._mouseHandlerBound,!1);this._decorations[a].clear()}return!0};function AppVideoDialog(a){this._element=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._focusHandlerBound=this._focusHandler.bind(this);this._keydownHandlerBound=this._keydownHandler.bind(this);this._closeButtonClickHandlerBound=this._closeButtonClickHandler.bind(this);this._element.setAttribute("role","dialog");this._element.setAttribute("aria-labelledby","video-title");this._content=this._element.getElementsByClassName("app_video-content")[0];this._iframe=this._content.getElementsByTagName("IFRAME")[0];
this._iframeSrc=this._iframe.src;this._iframe.src="";this._element.insertAdjacentHTML("afterbegin",'<div class="app_video-backdrop"></div>');this._element.getElementsByClassName("app_video-backdrop")[0].addEventListener("click",this._closeButtonClickHandlerBound,!1);this._content.insertAdjacentHTML("beforeend",'<button class="app_video-close"><span class="app_video-close-label">Close</span><span class="app_video-close-decoration"></span></button>');this._closeButton=this._content.getElementsByClassName("app_video-close")[0];
this._closeButton.addEventListener("click",this._closeButtonClickHandlerBound,!1)}Object.defineProperty(AppVideoDialog.prototype,"element",{get:function(){return this._element}});AppVideoDialog.prototype._window=null;AppVideoDialog.prototype._document=null;AppVideoDialog.prototype._element=null;AppVideoDialog.prototype._content=null;AppVideoDialog.prototype._opened=!1;AppVideoDialog.prototype._closeButton=null;AppVideoDialog.prototype._iframe=null;AppVideoDialog.prototype._iframeSrc=null;
AppVideoDialog.prototype._focusHandlerBound=null;AppVideoDialog.prototype._keydownHandlerBound=null;AppVideoDialog.prototype._closeButtonClickHandlerBound=null;AppVideoDialog.prototype._lastActiveElement=null;
AppVideoDialog.prototype.open=function(){this._opened||(this._iframe.src=this._iframeSrc,this._opened=!0,this._document.body.classList.add("body--modal"),this._element.classList.add("app_video--opened"),this._lastActiveElement=this._document.activeElement,this._element.tabIndex=-1,this._element.focus(),this._document.addEventListener("focus",this._focusHandlerBound,!0),this._document.addEventListener("keydown",this._keydownHandlerBound,!0))};
AppVideoDialog.prototype._focusHandler=function(a){this._element.contains(a.target)||(a.stopPropagation(),this._element.focus())};AppVideoDialog.prototype._keydownHandler=function(a){27==a.keyCode&&this.close()};
AppVideoDialog.prototype.close=function(){this._opened&&(this._document.removeEventListener("focus",this._focusHandlerBound,!0),this._document.removeEventListener("keydown",this._keydownHandlerBound,!0),this._opened=!1,this._document.body.classList.remove("body--modal"),this._element.classList.remove("app_video--opened"),this._iframe.src="",this._element.removeAttribute("tabindex"),this._lastActiveElement.focus(),this._lastActiveElement=null)};
AppVideoDialog.prototype._closeButtonClickHandler=function(a){a.preventDefault();this.close()};AppVideoDialog.prototype.clear=function(){this._document.removeEventListener("focus",this._focusHandlerBound,!0);this._document.removeEventListener("keydown",this._keydownHandlerBound,!0);this._element.getElementsByClassName("app_video-backdrop")[0].removeEventListener("click",this._closeButtonClickHandlerBound,!1);this._closeButton.removeEventListener("click",this._closeButtonClickHandlerBound,!1);return!0};function BackgroundLayer(a){WebGLLayer.call(this,a);this.colors=[{index:50,brightness:0,contrast:7,r:255,g:43,b:47}]}BackgroundLayer.prototype=Object.create(WebGLLayer.prototype);BackgroundLayer.prototype.constructor=BackgroundLayer;BackgroundLayer.prototype.colors=null;BackgroundLayer.prototype.getRectCoords=function(a,b,c,d){return[0,0,c,0,0,d,0,d,c,0,c,d]};BackgroundLayer.prototype.getTexCoords=function(a,b){return[0,0,1,0,0,1,0,1,1,0,1,1]};
BackgroundLayer.prototype.getColor=function(a,b){var c,d,e,f;if(this.colors[0].index>=a)return this.colors[0];if(this.colors[this.colors.length-1].index<=a)return this.colors[this.colors.length-1];d=0;for(c=this.colors.length;d<c;d++)if(this.colors[d].index<=a&&this.colors[d+1].index>=a)return c=this.colors[d],d=this.colors[d+1],e=(a-c.index)/(d.index-c.index),f=(d.index-a)/(d.index-c.index),{r:f*c.r+e*d.r,g:f*c.g+e*d.g,b:f*c.b+e*d.b,contrast:f*c.contrast+e*d.contrast,brightness:f*c.brightness+e*
d.brightness}};BackgroundLayer.prototype.getTexture=function(a,b){return this.textures[0]};function Contact(a){if(null===a)throw new TypeError("Invalid element.");this._element=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._focusChangeHandlerBound=this._focusChangeHandler.bind(this);this._mouseMoveHandlerBound=this._mouseMoveHandler.bind(this);this._submitHandlerBound=this._submitHandler.bind(this);this._loadHandlerBound=this._loadHandler.bind(this);this._form=this._element.getElementsByClassName("contact_form")[0];this._form.addEventListener("submit",this._submitHandlerBound,
!1);this._fieldset=this._form.getElementsByClassName("contact_form-fieldset")[0];a=0;for(var b=this._window.location.search.substr(1).split("&"),c=b.length;a<c;a++){var d=b[a].split("=");d[0]in this._form.elements&&(this._form.elements[d[0]].value=1<d.length?d[1]:"")}(a=this._form.getElementsByClassName("contact_form-input--message")).length&&(this._messageInput=a[0],this._messageInput.addEventListener("focus",this._focusChangeHandlerBound,!1),this._messageInput.addEventListener("blur",this._focusChangeHandlerBound,
!1),this._messageInput.addEventListener("mouseenter",this._mouseMoveHandlerBound,!1),this._messageInput.addEventListener("mouseleave",this._mouseMoveHandlerBound,!1))}Contact.prototype._window=null;Contact.prototype._document=null;Contact.prototype._element=null;Contact.prototype._form=null;Contact.prototype._messageInput=null;Contact.prototype._focusChangeHandlerBound=null;Contact.prototype._mouseMoveHandlerBound=null;Contact.prototype._submitHandlerBound=null;
Contact.prototype._loadHandlerBound=null;Contact.prototype._sender=null;Contact.prototype._formEncoder=null;Contact.prototype._messageTimeoutID=0;Contact.prototype._fieldset=null;Contact.prototype._result=null;Contact.MESSAGE_TIMEOUT=3E3;Contact.prototype._focusChangeHandler=function(a){"focus"==a.type?this._form.classList.add("contact_form--message-input-focus"):this._form.classList.remove("contact_form--message-input-focus")};
Contact.prototype._mouseMoveHandler=function(a){"mouseenter"==a.type?this._form.classList.add("contact_form--message-input-hover"):this._form.classList.remove("contact_form--message-input-hover")};
Contact.prototype._submit=function(){this._endResultMessage();var a=FormDataReader.getEntries(this._form);this._sender?this._sender.abort():(this._sender=new XMLHttpRequest,this._sender.addEventListener("load",this._loadHandlerBound,!1),this._formEncoder=new FormDataEncoder);this._sender.open(this._form.method,this._form.dataset.action);this._sender.setRequestHeader("Content-Type","application/x-www-form-urlencoded; charset=UTF-8");this._formEncoder.encode(a);this._sender.send(this._formEncoder.result)};
Contact.prototype._submitHandler=function(a){this._submit();a.preventDefault()};
Contact.prototype._loadHandler=function(a){a=JSON.parse(this._sender.responseText);this._form.elements.nonce_time.value=a.nonce_time;this._form.elements.nonce.value=a.nonce;var b=1==a.code;b&&(this._form.elements.message.value="");this._form.classList.add("contact_form--result");this._result=this._document.createElement("div");this._result.className="contact_form-result-container";var c=this._document.createElement("div");c.className="contact_form-result "+(b?"contact_form-result--success":"contact_form-result--error");
b=this._document.createElement("p");b.className="contact_form-result-content";b.textContent=a.message;c.appendChild(b);this._result.appendChild(c);this._fieldset.parentNode.insertBefore(this._result,this._fieldset);this._messageTimeoutID=setTimeout(this._messageTimeoutHandler.bind(this),Contact.MESSAGE_TIMEOUT)};Contact.prototype._endResultMessage=function(){this._form.classList.remove("contact_form--result");this._result&&(this._result.parentNode.removeChild(this._result),this._result=null)};
Contact.prototype._messageTimeoutHandler=function(){this._endResultMessage()};
Contact.prototype.clear=function(){clearTimeout(this._messageTimeoutID);this._messageInput&&(this._messageInput.removeEventListener("focus",this._focusChangeHandlerBound,!1),this._messageInput.removeEventListener("blur",this._focusChangeHandlerBound,!1),this._messageInput.removeEventListener("mouseenter",this._mouseMoveHandlerBound,!1),this._messageInput.removeEventListener("mouseleave",this._mouseMoveHandlerBound,!1));this._sender&&(this._sender.removeEventListener("load",this._loadHandlerBound,
!1),this._sender.abort());this._form.removeEventListener("submit",this._submitHandlerBound,!1)};function DDSReader(){this.mipmaps=[]}DDSReader.DDS_MAGIC=542327876;DDSReader.DDS_FLAG_MIPMAPCOUNT_MASK=131072;DDSReader.DDS_HEADER_LENGTH=31;DDSReader.DDS_MAGIC_POS=0;DDSReader.DDS_SIZE_POS=1;DDSReader.DDS_FLAGS_POS=2;DDSReader.DDS_HEIGHT_POS=3;DDSReader.DDS_WIDTH_POS=4;DDSReader.DDS_MIPMAP_COUNT_POS=7;DDSReader.DDS_PFFLAGS_POS=20;DDSReader.DDS_FOURCC_POS=21;DDSReader.DDS_PFFLAG_FOURCC_MASK=4;DDSReader.FOURCC_DXT1=827611204;DDSReader.FOURCC_DXT5=894720068;DDSReader.RGB_S3TC_DXT1="rgb_s3tc_dxt1";
DDSReader.RGBA_S3TC_DXT1="rgba_s3tc_dxt1";DDSReader.RGBA_S3TC_DXT3="rgba_s3tc_dxt3";DDSReader.RGBA_S3TC_DXT5="rgba_s3tc_dxt5";DDSReader.prototype.mipmaps=null;
DDSReader.prototype._validate=function(a){a=new Int32Array(a,0,DDSReader.DDS_HEADER_LENGTH);if(a[DDSReader.DDS_MAGIC_POS]!=DDSReader.DDS_MAGIC)throw Error("Invalid magic number in DDS header");if(!a[DDSReader.DDS_PFFLAGS_POS]&DDSReader.DDS_PFFLAG_FOURCC_MASK)throw Error("Unsupported format, must contain a FourCC code");a=a[DDSReader.DDS_FOURCC_POS];if(a!=DDSReader.FOURCC_DXT1&&a!=DDSReader.FOURCC_DXT5)throw Error("Unsupported FourCC code: "+String.fromCharCode(a&255,a>>8&255,a>>16&255,a>>24&255));
};
DDSReader.prototype.read=function(a){this._validate(a);var b=new Int32Array(a,0,DDSReader.DDS_HEADER_LENGTH),c,d,e,f,g,h,k;switch(b[DDSReader.DDS_FOURCC_POS]){case DDSReader.FOURCC_DXT1:c=8;d=DDSReader.RGBA_S3TC_DXT1;break;case DDSReader.FOURCC_DXT5:c=16;d=DDSReader.RGBA_S3TC_DXT5;break;default:return 0}h=1;b[DDSReader.DDS_FLAGS_POS]&DDSReader.DDS_FLAG_MIPMAPCOUNT_MASK&&(h=Math.max(1,b[DDSReader.DDS_MIPMAP_COUNT_POS]));e=b[DDSReader.DDS_WIDTH_POS];f=b[DDSReader.DDS_HEIGHT_POS];g=b[DDSReader.DDS_SIZE_POS]+4;
for(k=0;k<h;++k)b=Math.max(4,e)/4*Math.max(4,f)/4*c,this.mipmaps.push(new DDSMipmapLevel(k,e,f,d,a.slice(g,g+b))),g+=b,e*=.5,f*=.5;return h};function DDSMipmapLevel(a,b,c,d,e){this.level=a;this.width=b;this.height=c;this.format=d;this.data=e}DDSMipmapLevel.prototype.format=null;DDSMipmapLevel.prototype.level=null;DDSMipmapLevel.prototype.width=null;DDSMipmapLevel.prototype.height=null;DDSMipmapLevel.prototype.data=null;function Ease(){}Ease.outQuart=function(a,b,c){return b+(b-c)*(Math.pow(a-1,4)-1)};function FormDataEncoder(){this._fileLoadEndedHandlerBound=this._fileLoadEndedHandler.bind(this)}FormDataEncoder.prototype._result=null;FormDataEncoder.prototype._readyState=0;FormDataEncoder.prototype._entries=null;FormDataEncoder.prototype._filesEntries=null;FormDataEncoder.prototype._filesReaders=null;FormDataEncoder.prototype._numLoadedFiles=0;FormDataEncoder.prototype._asyncEnd=null;Object.defineProperty(FormDataEncoder.prototype,"result",{get:function(){return this._result}});
Object.defineProperty(FormDataEncoder.prototype,"readyState",{get:function(){return this._readyState}});FormDataEncoder.EMPTY=0;FormDataEncoder.LOADING=1;FormDataEncoder.DONE=2;FormDataEncoder._ASYNC_HASH="hash";FormDataEncoder._ASYNC_ENC_FORM_DATA="encode_form-data";FormDataEncoder.normalizeEntryField=function(a){return a.replace(/\r([^\n]|$)/g,"\r\n$0").replace(/(^|[^\r])\n/g,"$0\r\n")};
FormDataEncoder.prototype.encode=function(a,b){if(this._readyState!=FormDataEncoder.EMPTY&&this._readyState!=FormDataEncoder.DONE)throw Error("Invalid call");this._result=null;var c="";void 0===b&&(b="application/x-www-form-urlencoded");var d,e,f,g=a.length;switch(b){case "application/x-www-form-urlencoded":for(f=0;f<g;f++)d=a[f],d.name&&(0==f&&"isindex"==d.name?c+=encodeURIComponent(d.value):(e="file"==d.type?d.value.name:"_charset_"==d.name&&"hidden"==d.type?"UTF-8":d.value,0<f&&(c+="&"),c+=encodeURIComponent(d.name)+
"="+encodeURIComponent(e)));this._result=c.replace(/%20/g,"+");this._readyState=FormDataEncoder.DONE;break;case "multipart/form-data":c=[];this._entries=a;for(f=0;f<g;f++)d=a[f],"file"==d.type&&c.push(d);0<c.length?(this._readyState=FormDataEncoder.LOADING,this._loadFiles(c)):this._encodeFormData();break;case "text/plain":for(f=0;f<g;f++)d=a[f],e="file"==d.type?d.value.name:"_charset_"==d.name&&"hidden"==d.type?"UTF-8":d.value,c+=d.name+"="+e+"\r\n";this._result=c;this._readyState=FormDataEncoder.DONE;
break;default:throw new TypeError("Invalid encoding");}};FormDataEncoder.prototype._loadFiles=function(a){this._filesEntries=a;a=a.length;this._filesReaders=Array(a);this._numLoadedFiles=0;for(var b,c=0;c<a;c++)b=new FileReader,this._filesReaders[c]=b,b.addEventListener("loadend",this._fileLoadEndedHandlerBound),b.readAsBinaryString((void 0).value)};
FormDataEncoder.prototype.hash=function(a,b){if(this._readyState!=FormDataEncoder.EMPTY&&this._readyState!=FormDataEncoder.DONE)throw Error("Invalid call");var c,d,e;this._entries=a;var f=[];if(!b)for(d=0,e=a.length;d<e;d++)c=a[d],"file"==c.type&&f.push(f);0<f.length?(this._result=null,this._readyState=FormDataEncoder.LOADING,this._loadFiles(f)):this._generateHash()};
FormDataEncoder.prototype._fileLoadEndedHandler=function(a){if(a.target.error)throw this._release(!0),this._result=null,this._readyState=FormDataEncoder.EMPTY,Error("File read error: "+a.target.error.name);if(++this._numLoadedFiles>this._filesReaders.length)switch(this._asyncEnd){case FormDataEncoder._ASYNC_HASH:this._generateHash();break;case FormDataEncoder._ASYNC_ENC_FORM_DATA:this._encodeFormData()}};
FormDataEncoder.prototype._release=function(a){for(var b,c=0,d=this._filesReaders;c<d;c++)b=this._filesReaders[c],b.removeEventListener("loadend",this._fileLoadEndedHandlerBound),a&&b.abort();this._filesEntries=this._filesReaders=this._entries=null;this._numLoadedFiles=0};
FormDataEncoder.prototype._generateHash=function(){var a="",b,c,d=this._entries.length;if(0<this._numLoadedFiles)for(c=0;c<d;c++)b=this._entries[c],a="file"==b.type?a+(b.name+b.value.name+this._filesReaders[this._filesEntries.indexOf(b)].result):a+(b.name+b.value);else for(c=0;c<d;c++)b=this._entries[c],a="file"==b.type?a+(b.name+b.value.name+b.value.size+b.value.type+b.value.lastModifiedDate.value):a+(b.name+b.value);b=5381;for(c=0;c<a.length;c++)b=(b<<5)+b+a.charCodeAt(c);this._release();this._result=
b;this._readyState=FormDataEncoder.DONE};FormDataEncoder.prototype._encodeFormData=function(){this._release();this._result="";this._readyState=FormDataEncoder.DONE};function FormDataReader(){}
FormDataReader.getEntries=function(a){this._data=null;for(var b=[],c,d,e,f,g=0,h=a.elements.length;g<h;g++)if(f=a.elements[g],c=f.type,d=f.name,e=f.nodeName,!("FIELDSET"==e||"OUTPUT"==e||f.matches(":disabled")||"BUTTON"==e||"INPUT"==e&&"reset"==c||"INPUT"==e&&"submit"==c||"INPUT"==e&&"image"==c||"INPUT"==e&&"checkbox"==c&&"radio"==c&&!f.checked)&&d&&"OBJECT"!=e)if("SELECT"==e)for(var k=0,l=f.selectedOptions.length;k<l;k++)e=f.selectedOptions[k],e.matches(":disabled")||b.push(new FormDataEntry(d,e.value,
c));else if("INPUT"!=e||"radio"!=c&&"checkbox"!=c)if("INPUT"==e&&"file"==c){e=0;k=f.files.length;for(e=0;e<k;e++)b.push(new FormDataEntry(d,f.files[e],c));0==k&&b.push(new FormDataEntry(d,"","application/octet-stream"))}else"OBJECT"==e?b.push(new FormDataEntry(d,"%plugin value%","object")):(("TEXTAREA"==e||"INPUT"==e&&("text"==c||"search"==c))&&f.hasAttribute("dirname")&&f.dirName&&b.push(new FormDataEntry(f.dirName,f.matches(":dir(rtl)")?"rtl":"ltr","direction")),b.push(new FormDataEntry(d,f.value,
c)));else b.push(new FormDataEntry(d,f.value,c));return b};FormDataReader.toFormData=function(a,b){if(a instanceof HTMLFormElement&&!(b instanceof FormData))return new FormData(a);b=b instanceof FormData?b:new FormData;for(var c,d=0,e=a.length;d<e;d++)c=a[d],b.append(c.name,c.value);return b};function FormDataEntry(a,b,c){this.name=a;this.value=b;this.type=c};function Header(a){if(null===a)throw new TypeError("Invalid element.");this._element=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._document.addEventListener("scroll",this._scrollHandler.bind(this),!1);this._scrollHandler();this._links=this._element.getElementsByClassName("header_nav-link");a=this._linkClickHandler.bind(this);for(var b=0,c=this._links.length;b<c;b++)this._links[b].addEventListener("click",a,!1);this._element.getElementsByClassName("header_title-link")[0].addEventListener("click",
a,!1)}Header.HEIGHT=78;Header.STICKY_HEIGHT=43;Header.prototype._window=null;Header.prototype._document=null;Header.prototype._element=null;Header.prototype._links=null;Header.prototype._scrollHandler=function(a){this._window.scrollY>Header.HEIGHT-Header.STICKY_HEIGHT?this._element.classList.add("header--sticky"):this._element.classList.remove("header--sticky")};
Header.prototype._linkClickHandler=function(a){if(!(0!=a.button||a.altKey||a.ctrlKey||a.metaKey)){a=a.currentTarget;for(var b,c=0,d=this._links.length;c<d;c++)b=this._links[c],b===a?b.classList.add("header_nav-link--current"):b.classList.remove("header_nav-link--current")}};function Home(a){if(null===a)throw new TypeError("Invalid element.");this._element=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._wheelHandlerBound=this._wheelHandler.bind(this);this._scrollHandlerBound=this._scrollHandler.bind(this);this._keydownHandlerBound=this._keydownHandler.bind(this);this._skipClickHandlerBound=this._skipClickHandler.bind(this);this._scrollAnimationFrameHandlerBound=this._scrollAnimationFrameHandler.bind(this);this._userScrollTimeoutHandlerBound=
this._userScrollTimeoutHandler.bind(this);this._anchorClickHandlerBound=this._anchorClickHandler.bind(this);var b;(b=a.getElementsByClassName("index_apps-canvas")).length&&(this._objectVR=new ObjectVR(b[0]));(b=a.getElementsByClassName("index_strong-points-content")).length&&(this._contentElement=b[0]);var c;if(b=(this._strongPointsElements=a.getElementsByClassName("index_strong-point")).length)for(c=0;c<b;c++)this._strongPointsElements[c].classList.remove("index_strong-point--target");b&&this._updateStrongPointStyles();
if(b&&(b=(this._anchorsElements=a.getElementsByClassName("index_strong-points-toc-anchor")).length))for(c=0;c<b;c++)this._anchorsElements[c].classList.remove("index_strong-points-toc-anchor--target"),this._anchorsElements[c].addEventListener("click",this._anchorClickHandlerBound,!1);(b=a.getElementsByClassName("index_apps-skip")).length&&(this._skipElement=b[0],this._skipElement.addEventListener("click",this._skipClickHandlerBound,!1));this._document.addEventListener("wheel",this._wheelHandlerBound,
!1);this._window.addEventListener("scroll",this._scrollHandlerBound,!1);this._document.addEventListener("keydown",this._keydownHandlerBound,!1);this._updatePosition(0)}Home.POSITION_PIXEL=100;Home.POSITION_LINES=3;Home.SCROLL_TRANSITION_DURATION=400;Home.AUTO_SCROLL_DELAY=200;Home.prototype._window=null;Home.prototype._document=null;Home.prototype._element=null;Home.prototype._contentElement=null;Home.prototype._skipElement=null;Home.prototype._anchorsElements=null;
Home.prototype._strongPointsElements=null;Home.prototype._currentStrongPointIndex=-1;Home.prototype._position=-1;Home.prototype._objectVR=null;Home.prototype._deltaY=0;Home.prototype._deltaMode=0;Home.prototype._wheelTime=0;Home.prototype._scrollTransitionCurrentX=NaN;Home.prototype._scrollTransitionCurrentY=NaN;Home.prototype._scrollTransitionToX=NaN;Home.prototype._scrollTransitionToY=NaN;Home.prototype._scrollTransitionFromX=NaN;Home.prototype._scrollTransitionFromY=NaN;
Home.prototype._scrollTransiting=!1;Home.prototype._scrollTransitionStart=0;Home.prototype._scrollAnimationFrameHandlerBound=null;Home.prototype._scrollAnimationFrameRequestID=null;Home.prototype._userScrollTimeoutID=null;Home.prototype._userScrollTimeoutHandlerBound=null;Home.prototype._wheelHandlerBound=null;Home.prototype._scrollHandlerBound=null;Home.prototype._keydownHandlerBound=null;Home.prototype._skipClickHandlerBound=null;Home.prototype._anchorClickHandlerBound=null;
Home.prototype._updateStrongPointStyles=function(){var a=this._element.querySelector(".index_strong-point-style");if(a)for(var a=a.sheet.cssRules,b=/url\('([^']*)|url\("([^"]*)|url\(([^\)]*)/,c=0,d=a.length,e;c<d;c++)e=a[c],e.type==CSSRule.STYLE_RULE&&".index_strong-point-title::before"==e.selectorText.substr(-33)&&e.style.backgroundImage&&(e=(e=b.exec(e.style.backgroundImage))?e[1]||e[2]||e[3]:null,(new Image).src=e)};Home.prototype._skipClickHandler=function(a){a.preventDefault();this._updatePosition(1)};
Home.prototype._targetStrongPoint=function(a){var b,c,d,e;a=Math.max(Math.min(a,this._strongPointsElements.length-1),-1);if(a!=this._currentStrongPointIndex){this._currentStrongPointIndex=a;d=0;for(e=this._strongPointsElements.length;d<e;d++)b=this._strongPointsElements[d],c=b.classList,d==a?(c.remove("index_strong-point--untarget"),c.add("index_strong-point--target"),this._contentElement.style.backgroundColor=b.dataset.color):c.contains("index_strong-point--target")&&(c.remove("index_strong-point--target"),
c.add("index_strong-point--untarget"));d=0;for(e=this._anchorsElements.length;d<e;d++)b=this._anchorsElements[d],c=b.classList,d==a?(c.remove("index_strong-points-toc-anchor--untarget"),c.add("index_strong-points-toc-anchor--target")):c.contains("index_strong-points-toc-anchor--target")&&(c.remove("index_strong-points-toc-anchor--target"),c.add("index_strong-points-toc-anchor--untarget"))}};
Home.prototype._anchorClickHandler=function(a){a.preventDefault();a=1+Array.prototype.indexOf.call(this._anchorsElements,a.currentTarget);this._updatePosition(a)};
Home.prototype._wheelHandler=function(a){0!=a.deltaY&&a.preventDefault();if(!(0<this._wheelTime&&400>Date.now()-this._wheelTime)){this._wheelTime=0;var b=a.deltaMode;a=(this._deltaMode==b?this._deltaY:0)+a.deltaY;this._deltaMode=b;var c=0;switch(b){case WheelEvent.DOM_DELTA_PIXEL:c=a/Home.POSITION_PIXEL|0;a%=Home.POSITION_PIXEL;break;case WheelEvent.DOM_DELTA_LINE:c=a/Home.POSITION_LINES|0;a%=Home.POSITION_LINES;break;case WheelEvent.DOM_DELTA_PAGE:c=a,a=0}c=Math.min(Math.max(c,-1),1);this._deltaY=
a;this._updatePosition(this._position+c)&&(this._wheelTime=Date.now())}};
Home.prototype._updatePosition=function(a){a=Math.max(Math.min(a,this._strongPointsElements.length),0);if(this._position!=a){this._position=a;var b=this._skipElement.classList;0==a?(this._objectVR.active=!0,b.add("index_apps-skip--active"),b.remove("index_apps-skip--inactive"),this._scrollTo(this._window.scrollX,0)):(this._objectVR.active=!1,b.remove("index_apps-skip--active"),b.add("index_apps-skip--inactive"),this._scrollTo(this._window.scrollX,this._window.scrollMaxY));this._targetStrongPoint(a-
1);return!0}return!1};Home.prototype._keydownHandler=function(a){switch(a.keyCode){case 38:case 34:a.preventDefault();this._updatePosition(this._position-1);break;case 40:case 33:a.preventDefault();this._updatePosition(this._position+1);break;case 32:a.preventDefault(),this._updatePosition((this._position+1)%(this._strongPointsElements.length+1))}};
Home.prototype._scrollTo=function(a,b){this._scrollTransitionFromX=this._window.scrollX;this._scrollTransitionFromY=this._window.scrollY;this._scrollTransitionToX=a;this._scrollTransitionToY=b;this._scrollTransitionStart=Date.now();this._clearUserScrollTimeout();this._scrollTransiting||(this._scrollTransiting=!0,this._scrollTransitionTick(0),this._scrollAnimationFrameRequestID=requestAnimationFrame(this._scrollAnimationFrameHandlerBound))};
Home.prototype._stopScrollTransition=function(){this._scrollTransiting&&(this._scrollTransiting=!1,cancelAnimationFrame(this._scrollAnimationFrameRequestID))};Home.prototype._scrollAnimationFrameHandler=function(a){a=(Date.now()-this._scrollTransitionStart)/Home.SCROLL_TRANSITION_DURATION;a=Math.min(Math.max(a,0),1);this._scrollTransitionTick(a);1==a?this._scrollTransiting=!1:this._scrollAnimationFrameRequestID=requestAnimationFrame(this._scrollAnimationFrameHandlerBound)};
Home.prototype._scrollTransitionTick=function(a){var b=Ease.outQuart(a,this._scrollTransitionFromX,this._scrollTransitionToX);a=Ease.outQuart(a,this._scrollTransitionFromY,this._scrollTransitionToY);this._scrollTransitionCurrentX=b;this._scrollTransitionCurrentY=a;this._window.scrollTo(Math.round(b),Math.round(a))};
Home.prototype._scrollHandler=function(a){this._clearUserScrollTimeout();this._scrollTransiting&&Math.round(this._scrollTransitionCurrentX)==this._window.scrollX&&Math.round(this._scrollTransitionCurrentY)==this._window.scrollY||(this._stopScrollTransition(),this._userScrollTimeoutID=setTimeout(this._userScrollTimeoutHandlerBound,Home.AUTO_SCROLL_DELAY))};
Home.prototype._clearUserScrollTimeout=function(){this._userScrollTimeoutID&&(clearTimeout(this._userScrollTimeoutID),this._userScrollTimeoutID=null)};Home.prototype._userScrollTimeoutHandler=function(){this._userScrollTimeoutID=null;var a=this._window.scrollY,b=this._window.scrollMaxY;a<b/2?0<this._position?this._updatePosition(0):0<a&&this._scrollTo(this._window.scrollX,0):1>this._position?this._updatePosition(1):a<b&&this._scrollTo(this._window.scrollX,b)};
Home.prototype.clear=function(){this._objectVR&&this._objectVR.clear();clearTimeout(this._userScrollTimeoutID);cancelAnimationFrame(this._scrollAnimationFrameRequestID);for(var a=0,b=this._anchorsElements.length;a<b;a++)this._anchorsElements[a].addEventListener("click",this._anchorClickHandlerBound,!1);this._skipElement&&this._skipElement.removeEventListener("click",this._skipClickHandlerBound,!1);this._document.removeEventListener("wheel",this._wheelHandlerBound,!1);this._window.removeEventListener("scroll",
this._scrollHandlerBound,!1);this._document.removeEventListener("keydown",this._keydownHandlerBound,!1);return!0};function ObjectVR(a){if(null===a||!(a instanceof HTMLCanvasElement))throw new TypeError("Not a valid HTMLCanvasElement element.");this._canvas=a;this._document=a.ownerDocument;this._window=this._document.defaultView;this._documentElement=this._document.documentElement;this._animationFrameHandlerBound=this._animationFrameHandler.bind(this);this._loadAnimationFrameHandlerBound=this._loadAnimationFrameHandler.bind(this);this._pointerEventHandlerBound=this._pointerEventHandler.bind(this);this._resizeHandlerBound=
this._resizeHandler.bind(this);this._deviceOrientationHandlerBound=this._deviceOrientationHandler.bind(this);this._orientationHandlerBound=this._orientationHandler.bind(this);var b;(b=this._document.getElementsByClassName("index_apps")).length&&(this._rootElement=b[0]);(b=this._rootElement.getElementsByClassName("index_apps-content")).length&&(this._contentElement=b[0]);this._positionIndicatorElements=this._document.getElementsByClassName("index_apps-position-indicator");this._instantTaglineElements=
this._document.getElementsByClassName("index_apps-instant-tagline");this._canvas.insertAdjacentHTML("afterend",'<div class="index_apps-loader">\n\t<svg class="index_apps-loader-decoration" role="presentation">\n\t\t<circle r="110" class="index_apps-loader-decoration-circle"></circle>\n\t</svg>\n</div>\n<div class="index_apps-position">\n\t<div class="index_apps-position-indicator"></div>\n\t<div class="index_apps-position-indicator"></div>\n\t<div class="index_apps-position-indicator"></div>\n</div>');
if((b=this._document.getElementsByClassName("index_apps-tagline")).length){for(var c,d=b[0],e=document.createDocumentFragment(),f=0;1>f;f++){b=d.cloneNode(!0);b.className="index_apps-instant-tagline index_apps-instant-tagline--index-"+f;b.setAttribute("role","presentation");for(c=b.firstElementChild;c;)c.className=c.className.replace(/index_apps-tagline(-|_|\s|$)/g,"index_apps-instant-tagline$1"),c=c.nextElementSibling;e.appendChild(b)}this._canvas.parentNode.insertBefore(e,this._canvas.nextSibling)}(b=
this._document.getElementsByClassName("index_apps-loader-decoration-circle")).length&&(this._loaderDecorationPathElement=this._prepareLoaderDecorationPath(b[0]));this._createScene(a);this._updateCanvasSizes();this._contentElement.addEventListener("mousemove",this._pointerEventHandlerBound,!1);this._window.addEventListener("resize",this._resizeHandlerBound,!1);this._window.addEventListener("orientationchange",this._orientationHandlerBound,!1);if(window.matchMedia&&window.matchMedia("(pointer: coarse), (touch-enabled: 1)").matches||
"ontouchstart"in window||Boolean(navigator.msMaxTouchPoints)||Boolean(navigator.maxTouchPoints))this._contentElement.addEventListener("touchstart",this._pointerEventHandlerBound,!1),this._contentElement.addEventListener("touchmove",this._pointerEventHandlerBound,!1),this._contentElement.addEventListener("touchend",this._pointerEventHandlerBound,!1),this._window.addEventListener("deviceorientation",this._deviceOrientationHandlerBound,!1);this._orientation=this._window.orientation||0;this._sceneProgress=
0;this._sceneProgressLastTime=this._sceneProgressStartTime=Date.now();this._drawLoader();this._loadAnimationFrameRequestID=requestAnimationFrame(this._loadAnimationFrameHandlerBound);this._scene.onload=this._sceneLoadHandler.bind(this);this._scene.onprogress=this._sceneProgressHandler.bind(this);this._scene.load()}ObjectVR.prototype._document=null;ObjectVR.prototype._documentElement=null;ObjectVR.prototype._window=null;ObjectVR.prototype._canvas=null;ObjectVR.prototype._contentElement=null;
ObjectVR.prototype._loaderDecorationPathElement=null;ObjectVR.prototype._scene=null;ObjectVR.prototype._animationFrameRequestID=0;ObjectVR.prototype._positionIndicatorElements=null;ObjectVR.prototype._positionIndicator=-1;ObjectVR.prototype._instantTaglineElements=null;ObjectVR.prototype._instantTagline=-1;ObjectVR.prototype._active=!0;ObjectVR.prototype._animationFrameHandlerBound=null;ObjectVR.prototype._loadAnimationFrameHandlerBound=null;ObjectVR.prototype._loadAnimationFrameRequestID=0;
ObjectVR.prototype._lastFrameTime=0;ObjectVR.prototype._positionX=0;ObjectVR.prototype._positionY=0;ObjectVR.prototype._endPositionX=0;ObjectVR.prototype._endPositionY=0;ObjectVR.prototype._sceneProgress=0;ObjectVR.prototype._sceneProgressLastTime=0;ObjectVR.prototype._sceneProgressStartTime=0;ObjectVR.prototype._dirty=!1;ObjectVR.prototype._width=0;ObjectVR.prototype._height=0;ObjectVR.prototype._orientation=0;ObjectVR.prototype._pointerEventHandlerBound=null;
ObjectVR.prototype._resizeHandlerBound=null;ObjectVR.prototype._deviceOrientationHandlerBound=null;ObjectVR.prototype._orientationHandlerBound=null;ObjectVR.prototype._useTouch=!1;ObjectVR.MOTION_DURATION=1E3;ObjectVR.AREA_PADDING_X=60;ObjectVR.AREA_PADDING_Y=140;ObjectVR.AREA_MAX_WIDTH=1200;ObjectVR.AREA_MAX_HEIGHT=800;Object.defineProperty(ObjectVR.prototype,"active",{set:function(a){(this._active=Boolean(a))&&this._setDirty()},get:function(){return this._active}});
ObjectVR.prototype._sceneLoadHandler=function(a){window.cancelAnimationFrame(this._loadAnimationFrameRequestID);this._rootElement.classList.add("index_apps--loaded");this._positionX=1;this._positionY=.5;this._endPositionX=0;this._endPositionY=.5;this._setDirty(!0)};ObjectVR.prototype._prepareLoaderDecorationPath=function(a){var b=parseFloat(a.getAttribute("r"))*Math.PI*2+2;a.style.strokeDashoffset=String(b)+"px";a.style.strokeDasharray=b+"px "+b+"px";return a};
ObjectVR.prototype._sceneProgressHandler=function(a){a.lengthComputable&&(this._sceneProgress=a.loaded/a.total,this._sceneProgressLastTime=Date.now(),1==this._sceneProgress&&(this._drawLoader(),cancelAnimationFrame(this._loadAnimationFrameRequestID)))};
ObjectVR.prototype._drawLoader=function(){var a=Date.now(),a=Math.min((0==this._sceneProgress?0:this._sceneProgress/(this._sceneProgressLastTime-this._sceneProgressStartTime))*(a-this._sceneProgressStartTime),1),a=Transition.cubicIn(a),b=parseFloat(this._loaderDecorationPathElement.getAttribute("r"))*Math.PI*2+2;this._loaderDecorationPathElement.style.strokeDashoffset=String(b*(1-a))+"px"};
ObjectVR.prototype._loadAnimationFrameHandler=function(){this._drawLoader();1>this._sceneProgress&&(this._loadAnimationFrameRequestID=requestAnimationFrame(this._loadAnimationFrameHandlerBound))};ObjectVR.prototype._animationFrameHandler=function(){this._animationFrameRequestID=0;this._drawScene()};
ObjectVR.prototype._drawScene=function(){this._dirty=!1;if(this._scene.loaded&&this.active){var a=Date.now(),b=a-this._lastFrameTime,c=Math.max(Math.min(.008*(this._endPositionX-this._positionX),.002),-.002),d=Math.max(Math.min(.012*(this._endPositionY-this._positionY),.008),-.008),e=this._positionX+c*b,b=this._positionY+d*b;2E-6>Math.abs(c)&&(e=this._endPositionX);2E-6>Math.abs(d)&&(b=this._endPositionY);this._scene.draw(e,b);this._updateIndicators(e);this._updateInstantTaglines(e);if(e!=this._positionX||
b!=this._positionY)this._lastFrameTime=a,this._animationFrameRequestID=requestAnimationFrame(this._animationFrameHandlerBound);this._positionX=e;this._positionY=b}};
ObjectVR.prototype._updateIndicators=function(a){var b,c,d=-1,d=a<=1/3?0:a<=2/3?1:2;if(d!=this._positionIndicator)for(this._positionIndicator=d,a=0,c=this._positionIndicatorElements.length;a<c;a++)b=this._positionIndicatorElements[a],b=b.classList,a==d?b.add("index_apps-position-indicator--current"):b.contains("index_apps-position-indicator--current")&&b.remove("index_apps-position-indicator--current")};
ObjectVR.prototype._updateInstantTaglines=function(a){var b,c,d=-1;.28>=a?d=0:.88<=a&&(d=0);if(d!=this._instantTagline)for(this._instantTagline=d,a=0,c=this._instantTaglineElements.length;a<c;a++)b=this._instantTaglineElements[a],b=b.classList,a==d?b.add("index_apps-instant-tagline--current"):b.contains("index_apps-instant-tagline--current")&&b.remove("index_apps-instant-tagline--current")};
ObjectVR.prototype._pointerEventHandler=function(a){var b=this._contentElement.getBoundingClientRect().top;if("touchstart"==a.type)this._useTouch=!0;else if("touchend"==a.type){this._useTouch=!1;return}var c;"touches"in a?(c=a.touches[0].pageX,a=a.touches[0].pageY-b):(c=a.pageX,a=a.pageY-b);var b=Math.max((this._width-ObjectVR.AREA_MAX_WIDTH)/2,ObjectVR.AREA_PADDING_X),d=Math.max((this._height-ObjectVR.AREA_MAX_HEIGHT)/2,ObjectVR.AREA_PADDING_Y);this._endPositionX=Math.min(Math.max((c-b)/(this._width-
2*b),0),1);this._endPositionY=Math.min(Math.max((a-d-46)/(this._height-2*d-46),0),1);this._setDirty(!0)};ObjectVR.prototype._updateCanvasSizes=function(a){this._width=this._canvas.clientWidth;this._height=this._canvas.clientHeight;a=this._window.devicePixelRatio;this._scene.updateSize(this._canvas.width=this._width*a,this._canvas.height=this._height*a);this._setDirty()};
ObjectVR.prototype._setDirty=function(a){if(!this._dirty){this._dirty=!0;var b=0!==this._animationFrameRequestID;if(!b||a)this._lastFrameTime=Date.now();b||(this._animationFrameRequestID=requestAnimationFrame(this._animationFrameHandlerBound))}};ObjectVR.prototype._resizeHandler=function(){this._updateCanvasSizes()};
ObjectVR.prototype._deviceOrientationHandler=function(a){if(!this._useTouch){var b=Math.PI,c=a.gamma*Math.cos(this._orientation/180*b)+a.beta*Math.sin(this._orientation/180*b);a=a.beta*Math.cos(this._orientation/180*b)+a.gamma*Math.sin(-this._orientation/180*b);this._endPositionX=Math.max(Math.min(c,10),-10)/10*.5+.5;this._endPositionY=Math.max(Math.min(a,10),-10)/10*.5+.5;this._setDirty(!0)}};ObjectVR.prototype._orientationHandler=function(a){this._orientation=this._window.orientation};
ObjectVR.prototype._createScene=function(a){if(WebGLScene.test(a)){var b=new BackgroundLayer("background");b.blending={separate:!1,sFactor:WebGLRenderingContext.DST_COLOR,dFactor:WebGLRenderingContext.SRC_COLOR};b.colors=[{index:39/211,brightness:-36,contrast:20,r:255,g:43,b:47},{index:98/211,brightness:0,contrast:0,r:255,g:200,b:57},{index:150/211,brightness:0,contrast:0,r:15,g:206,b:64}];var c=new WebGLLayer("object");c.depth=.35;var d=new WebGLLayer("shadow");d.depth=.05;d.zoomLevel=1.1;d.zoomOffsetX=
.1;d.blending={separate:!1,sFactor:WebGLRenderingContext.DST_COLOR,dFactor:WebGLRenderingContext.ZERO};var e=new WebGLLayer("phone");e.depth=1.15;this._scene=new WebGLScene(a,{src4096:this._canvas.dataset.srcWebgl4096,size4096:this._canvas.dataset.sizeWebgl4096,src2048:this._canvas.dataset.srcWebgl2048,size2048:this._canvas.dataset.sizeWebgl2048},[b,c,d,e])}else if(SimpleScene.test(a))this._scene=new SimpleScene(a,this._getURIsFromTemplate(this._canvas.dataset.src));else throw Error("Unable to create a valid Scene");
};ObjectVR.prototype._getURIsFromTemplate=function(a){var b,c,d=1,e,f,g,h,k;if(b=a.match(/\[(\d+):(\d+)(?::(\d+))?\]/)){h=a.substring(0,b.index);k=a.substr(b.index+b[0].length);a=parseInt(b[1],10);c=parseInt(b[2],10);e=b[1].length;3<b.length&&void 0!==b[3]&&(d=parseInt(b[3],10));b=Math.floor((c-a)/d)+1;g=Array(b);for(c=0;c<b;c++)f=String(a+c*d),f.length<e&&(f="0".repeat(e-f.length)+f),g[c]=h+f+k;return g}return[a]};
ObjectVR.prototype.clear=function(){this._contentElement.removeEventListener("mousemove",this._pointerEventHandlerBound,!1);this._contentElement.removeEventListener("touchstart",this._pointerEventHandlerBound,!1);this._contentElement.removeEventListener("touchmove",this._pointerEventHandlerBound,!1);this._contentElement.removeEventListener("touchend",this._pointerEventHandlerBound,!1);this._window.removeEventListener("resize",this._resizeHandlerBound,!1);this._window.removeEventListener("deviceorientation",
this._deviceOrientationHandlerBound,!1);this._window.removeEventListener("orientationchange",this._orientationHandlerBound,!1);cancelAnimationFrame(this._loadAnimationFrameRequestID);cancelAnimationFrame(this._animationFrameRequestID);this._scene&&(this._scene.onload=null,this._scene.onprogress=null,this._scene.clear());return!0};function Scene(a){this._element=a}Scene.prototype._context=null;Scene.prototype._loaded=!1;Object.defineProperty(Scene.prototype,"loaded",{get:function(){return this._loaded}});Scene.prototype.draw=function(a,b){};Scene.prototype.updateSize=function(a,b){};Scene.prototype._dispatchProgressEvent=function(a,b){"function"===typeof this.onprogress&&(a=void 0==a||null==a?0:Number(a),b=void 0==b||null==b?0:Number(b),this.onprogress({type:"progress",currentTarget:this,lengthComputable:0!=b,loaded:a,total:b}))};
Scene.prototype._dispatchLoadEvent=function(){if("function"===typeof this.onload)this.onload({type:"load",currentTarget:this})};Scene.prototype._dispatchErrorEvent=function(){if("function"===typeof this.onerror)this.onerror({type:"error",currentTarget:this})};Scene.prototype._dispatchAbortEvent=function(){if("function"===typeof this.onabort)this.onabort({type:"abort",currentTarget:this})};Scene.prototype.clear=function(){};function ScrollAnimator(a,b){this._root=a;this._elements=b;this._window=this._root instanceof Window?this._root:this._root.ownerDocument.defaultView;this._animationFrameHandlerBound=this._animationFrameHandler.bind(this);this._scrollHandlerBound=this._scrollHandler.bind(this);this._resizeHandlerBound=this._resizeHandler.bind(this);this._root.addEventListener("scroll",this._scrollHandlerBound,!0);this._window.addEventListener("resize",this._resizeHandlerBound,!0);this._setDirty()}
ScrollAnimator.IN_VIEWPORT_CLASS="element--in-viewport";ScrollAnimator.prototype._window=null;ScrollAnimator.prototype._root=null;ScrollAnimator.prototype._elements=null;ScrollAnimator.prototype._animationFrameRequestID=0;ScrollAnimator.prototype._animationFrameHandlerBound=null;ScrollAnimator.prototype._scrollHandlerBound=null;ScrollAnimator.prototype._resizeHandlerBound=null;ScrollAnimator.prototype._scrollHandler=function(a){this._setDirty()};ScrollAnimator.prototype._resizeHandler=function(a){this._setDirty()};
ScrollAnimator.prototype._checkElements=function(){for(var a=[],b=this._window.innerWidth,c=this._window.innerHeight,d=0,e=this._elements.length;d<e;d++){var f=this._elements[d],g=f.getBoundingClientRect(),h=Math.min(90,g.width),k=Math.min(90,g.height);g.left+h<b&&g.top+k<c&&!f.classList.contains(ScrollAnimator.IN_VIEWPORT_CLASS)&&a.push(f)}b=0;for(c=a.length;b<c;b++)a[b].classList.add(ScrollAnimator.IN_VIEWPORT_CLASS)};
ScrollAnimator.prototype._animationFrameHandler=function(){this._animationFrameRequestID=0;this._checkElements()};ScrollAnimator.prototype._setDirty=function(){0===this._animationFrameRequestID&&(this._animationFrameRequestID=requestAnimationFrame(this._animationFrameHandlerBound))};
ScrollAnimator.prototype.clear=function(){cancelAnimationFrame(this._animationFrameRequestID);this._root.removeEventListener("scroll",this._scrollHandlerBound,!0);this._window.removeEventListener("resize",this._resizeHandlerBound,!0)};function SimpleScene(a,b){Scene.call(this,a);this._context=a.getContext("2d");this._uris=b;this._numFrames=b.length;this._imagesLoadHandlerBound=this._imagesLoadHandler.bind(this)}SimpleScene.prototype=Object.create(Scene.prototype);SimpleScene.prototype.constructor=SimpleScene;SimpleScene.prototype._numFrames=0;SimpleScene.prototype._frames=null;SimpleScene.prototype._uris=null;SimpleScene.prototype._numFramesLoaded=0;SimpleScene.prototype._imagesLoadHandlerBound=null;
SimpleScene.prototype.draw=function(a,b){if(this._loaded){var c=this._frames[Math.round(a*(this._numFrames-1))],d=c.naturalWidth,e=c.naturalHeight,f=this._element.width,g=this._element.height,h=Math.min(d,e/g*f),d=h<d?(d-h)/2:0,k=Math.min(f,g/e*h);this._context.drawImage(c,d,0,h,e,k<f?(f-k)/2:0,0,k,g)}};SimpleScene.test=function(a){var b,c;a=a.cloneNode();try{b=a instanceof HTMLCanvasElement}catch(d){return!1}if(!b)return!1;try{c=a.getContext("2d")}catch(e){return!1}return null!==c};
SimpleScene.prototype.load=function(){this._numFramesLoaded=0;this._loaded=!1;this._frames=Array(this._numFrames);for(var a=0;a<this._numFrames;++a){var b=this._frames[a]=new Image;b.addEventListener("load",this._imagesLoadHandlerBound,!1);b.src=this._uris[a]}};
SimpleScene.prototype._imagesLoadHandler=function(a){a.currentTarget.removeEventListener("load",this._imagesLoadHandlerBound,!1);this._dispatchProgressEvent(this._numFramesLoaded,this._numFrames);++this._numFramesLoaded>=this._numFrames&&(this._loaded=!0,this._dispatchLoadEvent())};SimpleScene.prototype.clear=function(){Scene.prototype.clear.call(this);for(var a=0;a<this._numFrames;++a){var b=this._frames[a];b.removeEventListener("load",this._imagesLoadHandlerBound,!1);b.src=""}return!0};function TarReader(){this.files=[]}TarReader.BLOCK_SIZE=512;TarReader.NAME_OFFSET=0;TarReader.NAME_SIZE=100;TarReader.TYPE_OFFSET=156;TarReader.TYPE_SIZE=1;TarReader.SIZE_OFFSET=124;TarReader.SIZE_SIZE=12;TarReader.MAGIC_OFFSET=257;TarReader.MAGIC_SIZE=6;TarReader.PREFIX_OFFSET=345;TarReader.PREFIX_SIZE=155;TarReader.TYPE_FILE="0";TarReader.TYPE_DIR="5";TarReader.prototype._readString=function(a,b,c){var d="";a=new Uint8Array(a,b,c);for(var e=0;e<c;e++){b=a[e];if(0==b)break;d+=String.fromCharCode(b)}return d};
TarReader.prototype._readNumber=function(a,b,c){a=this._readString(a,b,c);return""===a?0:parseInt(a,8)};TarReader.prototype.files=null;TarReader.prototype._buffer=null;TarReader.prototype._offset=0;TarReader.prototype._endOfRecords=!1;
TarReader.prototype.readChunk=function(a){this._buffer=a;var b=this._offset,c=TarReader.BLOCK_SIZE,d=a.byteLength,e,f,g,h,k,l=!1;if(!this._endOfRecords){for(;b+c<=d;){e=this._readString(a,b+TarReader.TYPE_OFFSET,TarReader.TYPE_SIZE)||"0";f=this._readNumber(a,b+TarReader.SIZE_OFFSET,TarReader.SIZE_SIZE);if(isNaN(f))throw"Not a octal number! @0x"+b.toString(16);g=e==TarReader.TYPE_FILE?Math.ceil(f/c)*c:0;if(b+c+g>d)break;h=this._readString(a,b+TarReader.NAME_OFFSET,TarReader.NAME_SIZE);if(""==h&&e==
TarReader.TYPE_FILE){if(l){this._endOfRecords=!0;break}l=!0;b+=c}else{l&&(l=!1);k=this._readString(a,b+TarReader.MAGIC_OFFSET,TarReader.MAGIC_SIZE);if("ustar "===k||"ustar  "===k||"ustar"===k)switch(k=this._readString(a,b+TarReader.PREFIX_OFFSET,TarReader.PREFIX_SIZE),0<k.length&&"/"!=k.charAt(k.length-1)&&(k+="/"),h=k+h,e==TarReader.TYPE_DIR&&"/"!=h.charAt(h.length-1)&&(h+="/"),e){case TarReader.TYPE_FILE:e=b+c,this.files.push(new TarReaderFile(h,TarReaderFile.TYPE_FILE,a.slice(e,e+f)))}else console.log('Warning! Unsupported TAR record type:"'+
e+'", name:"'+h+'", magic:"'+k+'", size:"'+f+'"');b+=c+g}}this._offset=b}};TarReader.prototype.files=null;function TarReaderFile(a,b,c){this.name=a;this.type=b;this.data=c}TarReaderFile.TYPE_FILE=1;TarReaderFile.TYPE_DIR=2;TarReaderFile.prototype.name=null;TarReaderFile.prototype.type=null;TarReaderFile.prototype.data=null;function ThreeJuly(a){this._document=a.ownerDocument;this._window=this._document.defaultView;this._popstateHandlerBound=this._popstateHandler.bind(this);this._document.addEventListener("DOMContentLoaded",this._contentLoadedHandler.bind(this),!1)}ThreeJuly.prototype._window=null;ThreeJuly.prototype._document=null;ThreeJuly.prototype._header=null;ThreeJuly.prototype._objectVR=null;ThreeJuly.prototype._content=null;ThreeJuly.prototype._contentElement=null;ThreeJuly.prototype._nextContentElement=null;
ThreeJuly.prototype._completeWithContentEndTimeoutID=0;ThreeJuly.prototype._location=null;ThreeJuly.prototype._nextLocation=null;ThreeJuly.prototype._willPushState=!1;ThreeJuly.prototype._contentLoader=null;ThreeJuly.prototype._popstateHandlerBound=null;
ThreeJuly.prototype._contentLoadedHandler=function(a){this._document.removeEventListener("DOMContentLoaded",this._contentLoadedHandler.bind(this),!1);(a=document.getElementsByClassName("header")).length&&(this._header=new Header(a[0]));this._contentElement=this._document.getElementsByClassName("main")[0];"pushState"in window.history&&(this._document.addEventListener("click",this._clickHandler.bind(this),!1),this._window.addEventListener("popstate",this._popstateHandlerBound,!1),a=this._window.location,
this._location={pathname:a.pathname,search:a.search});this._initContent()};
ThreeJuly.prototype._clickHandler=function(a){if(a.defaultPrevented)a.preventDefault();else if(!(0!=a.button||a.altKey||a.ctrlKey||a.metaKey))for(var b=a.target,c=this._window.location,d,e;b;){if("A"==b.nodeName){if(""!=b.target&&"_self"!=b.target&&b.target!=this._window.name)break;d=c.href.indexOf("#");0>d&&(d=c.href.length);e=b.href.indexOf("#");0>e&&(e=b.href.length);b.protocol!=c.protocol||b.hostname!=c.hostname||b.port!=c.port&&(80!=b.port||""!=c.port)||b.href.substring(0,e)==c.href.substring(0,
d)&&b.href.substr(e)!=c.href.substr(d)||(a.preventDefault(),null==this._nextLocation&&(b.pathname!=c.pathname||b.search!=c.search)||b.pathname!=this._nextLocation.pathname||b.search!=this._nextLocation.search?this._loadContent(b,!0):null!=this._nextLocation&&b.href!=this._nextLocation.href&&this._updateNextLocation(b));break}b=b.parentElement}};
ThreeJuly.prototype._updateNextLocation=function(a){this._nextLocation?(this._nextLocation.href=a.href,this._nextLocation.pathname=a.pathname,this._nextLocation.search=a.search):this._nextLocation={href:a.href,pathname:a.pathname,search:a.search}};
ThreeJuly.prototype._popstateHandler=function(a){a=this._window.location;null==this._nextLocation&&(a.pathname!=this._location.pathname||a.search!=this._location.search)||null!=this._nextLocation&&(a.pathname!=this._nextLocation.pathname||a.search!=this._nextLocation.search)?this._loadContent(a,!1):null!=this._nextLocation&&a.href!=this._nextLocation.href&&this._updateNextLocation(a)};
ThreeJuly.prototype._loadContent=function(a,b){clearTimeout(this._completeWithContentEndTimeoutID);this._nextContentElement=null;this._contentElement.classList.remove("main--current");this._contentElement.offsetHeight;this._contentElement.classList.add("main--previous");this._updateNextLocation(a);this._willPushState=b;this._contentLoader?this._contentLoader.abort():(this._contentLoader=new XMLHttpRequest,this._contentLoader.addEventListener("load",this._contentLoadHandler.bind(this),!1),this._contentLoader.addEventListener("error",
this._contentErrorHandler.bind(this),!1));this._contentLoader.open("GET",this._nextLocation.href);this._contentLoader.send(null)};ThreeJuly.prototype._contentErrorHandler=function(a){a=this._document.createElement("main");this._completeWithContent(a)};
ThreeJuly.prototype._contentLoadHandler=function(a){a=this._contentLoader.getResponseHeader("Content-Type");if("string"!=typeof a||"text/html"!=a&&"text/html;"!=a.substr(0,10))this._window.location=this._nextLocation.href;else{this._contentParser||(this._contentParser=new DOMParser);var b,c;try{b=this._contentParser.parseFromString(this._contentLoader.responseText,"text/html")}catch(d){console.warn(d)}b&&(c=b.querySelector(".body .main"))?this._completeWithContent(c):this._window.location=this._nextLocation.href}};
ThreeJuly.prototype._completeWithContent=function(a){this._nextContentElement=a;this._completeWithContentEndTimeoutID=setTimeout(this._completeWithContentEnd.bind(this),400)};
ThreeJuly.prototype._completeWithContentEnd=function(a){this._willPushState&&this._window.history.pushState(null,null,this._nextLocation.href);this._location.pathname=this._nextLocation.pathname;this._location.search=this._nextLocation.search;this._nextLocation=null;this._content&&(this._content.clear(),this._content=null);this._contentElement&&(this._nextContentElement.ownerDocument!=this._document&&(this._document.title=this._nextContentElement.ownerDocument.title,this._document.body.className=
this._nextContentElement.ownerDocument.body.className+" body--js",this._nextContentElement=this._document.adoptNode(this._nextContentElement)),this._contentElement.parentNode.replaceChild(this._nextContentElement,this._contentElement));this._contentElement=this._nextContentElement;this._nextContentElement=null;this._initContent()};
ThreeJuly.prototype._initContent=function(a){this._contentElement.classList.contains("index_main")?this._content=new Home(this._contentElement):this._contentElement.classList.contains("apps_main")?this._content=new Apps(this._contentElement):this._contentElement.classList.contains("app_main")?this._content=new App(this._contentElement):this._contentElement.classList.contains("contact_main")&&(this._content=new Contact(this._contentElement));this._contentElement.classList.add("main--current");this._window.scrollTo(0,
0);a||"_gaq"in this._window&&this._window._gaq.push(["_trackPageview"])};var Transition={linear:function(a){return a},quadIn:function(a){return a*a},quadOut:function(a){return-a*(a-2)},quadInOut:function(a){return 1>(a*=2)?a*a*.5:-.5*(--a*(a-2)-1)},cubicIn:function(a){return a*a*a},cubicOut:function(a){return--a*a*a+1},cubicInOut:function(a){return 1>(a*=2)?Transition.cubicIn(a)/2:Transition.cubicOut(a-1)/2+.5},quartIn:function(a){return a*a*a*a},quartOut:function(a){a--;return-1*(a*a*a*a-1)},quartInOut:function(a){return 1>(a*=2)?Transition.quartIn(a)/2:Transition.quartOut(a-
1)/2+.5},quintIn:function(a){return a*a*a*a*a},quintOut:function(a){a--;return a*a*a*a*a+1},quintInOut:function(a){return 1>(a*=2)?Transition.quintIn(a)/2:Transition.quintOut(a-1)/2+.5},sineIn:function(a){return-1*Math.cos(a*Math.PI/2)+1},sineOut:function(a){return Math.sin(a*Math.PI/2)},sineInOut:function(a){return 1>(a*=2)?Transition.sineIn(a)/2:Transition.sineOut(a-1)/2+.5},expoIn:function(a){return 0==a?0:Math.pow(2,10*(a-1))-.001},expoOut:function(a){return.999<=a?1:1.001*(-Math.pow(2,-10*a)+
1)},expoInOut:function(a){return 1>(a*=2)?Transition.expoIn(a)/2:Transition.expoOut(a-1)/2+.5},circIn:function(a){return-1*(Math.sqrt(1-a*a)-1)},circOut:function(a){a--;return Math.sqrt(1-a*a)},circInOut:function(a){return 1>(a*=2)?Transition.circIn(a)/2:Transition.circOut(a-1)/2+.5},elasticIn:function(a,b,c){if(0==a)return 0;if(1==a)return 1;void 0===b&&(b=0);void 0===c&&(c=.3);var d;1>b?(b=1,d=c/4):d=c/(2*Math.PI)*Math.asin(1/b);return-(b*Math.pow(2,10*--a)*Math.sin(2*(a-d)*Math.PI/c))},elasticOut:function(a,
b,c){if(0==a)return 0;if(1==a)return 1;void 0===b&&(b=0);void 0===c&&(c=.3);var d;1>b?(b=1,d=c/4):d=c/(2*Math.PI)*Math.asin(1/b);return b*Math.pow(2,-10*a)*Math.sin(2*(a-d)*Math.PI/c)+1},backIn:function(a,b){void 0===b&&(b=1.70158);return a*a*((b+1)*a-b)},backOut:function(a,b){void 0===b&&(b=1.70158);a--;return a*a*((b+1)*a+b)+1},backInOut:function(a,b){void 0===b&&(b=1.70158);return 1>(a*=2)?Transition.backIn(a,b)/2:Transition.backOut(a-1,b)/2+.5},bounceIn:function(a){return 1-Transition.bounceOut(1-
a)},bounceOut:function(a){return a<1/2.75?7.5625*a*a:a<2/2.75?7.5625*(a-=1.5/2.75)*a+.75:a<2.5/2.75?7.5625*(a-=2.25/2.75)*a+.9375:7.5625*(a-=2.625/2.75)*a+.984375}};function WebGLLayer(a){this.name=a;this.textures=[];this.blending={separate:!1,sFactor:WebGLRenderingContext.SRC_ALPHA,dFactor:WebGLRenderingContext.ONE_MINUS_SRC_ALPHA}}WebGLLayer.prototype.name=null;WebGLLayer.prototype.textures=null;WebGLLayer.prototype.textureSize=4096;WebGLLayer.prototype.frames=null;WebGLLayer.prototype.blending=null;WebGLLayer.prototype.depth=0;WebGLLayer.prototype.zoomLevel=1;WebGLLayer.prototype.zoomOffsetX=0;WebGLLayer.prototype.zoomOffsetY=0;
WebGLLayer.prototype._getFrame=function(a,b){return this.frames?this.frames[Math.round(a*(this.frames.length-1))]:null};WebGLLayer.prototype.getTexCoords=function(a,b){var c=this._getFrame(a,b);if(c){var d=c.x/this.textureSize,e=c.y/this.textureSize,f=c.width/this.textureSize,c=c.height/this.textureSize;return[d,e,d+f,e,d,e+c,d,e+c,d+f,e,d+f,e+c]}return[0,0,0,0,0,0,0,0,0,0,0,0]};
WebGLLayer.prototype.getRectCoords=function(a,b,c,d){var e=this._getFrame(a,b);if(e){b=-this.depth*(1-b)/2;var f=d/1080,g=4096/this.textureSize;a=(e.sourceX*g-1460)*f*this.zoomLevel+c*this.zoomOffsetX*(a-.5)/2+c/2;d=(e.sourceY*g-540)*f*this.zoomLevel+d*this.zoomOffsetY*(b-.5)/2+d/2;c=e.width*g*f*this.zoomLevel;e=e.height*g*f*this.zoomLevel;return[a,d+d*b,a+c,d+d*b,a,d+e+d*b,a,d+e+d*b,a+c,d+d*b,a+c,d+e+d*b]}return[0,0,0,0,0,0,0,0,0,0,0,0]};
WebGLLayer.prototype.getTexture=function(a,b){var c=this._getFrame(a,b);return c?this.textures[c.id]:null};WebGLLayer.prototype.toString=function(){return'[object WebGLLayer name="'+this.name+'"]'};function WebGLScene(a,b,c,d){Scene.call(this,a);d=d||{alpha:!1};a=this._context=a.getContext("webgl",d)||a.getContext("experimental-webgl",d);this._s3tcExtension=a.getExtension("WEBGL_compressed_texture_s3tc")||a.getExtension("MOZ_WEBGL_compressed_texture_s3tc")||a.getExtension("WEBKIT_WEBGL_compressed_texture_s3tc");this._imagesLoadHandlerBound=this._imagesLoadHandler.bind(this);this._tarProgressHandlerBound=this._tarProgressHandler.bind(this);this._tarErrorHandlerBound=this._tarErrorHandler.bind(this);
this._tarAbortHandlerBound=this._tarAbortHandler.bind(this);this._tarLoadHandlerBound=this._tarLoadHandler.bind(this);this._layers=c||[];a=4096<=a.getParameter(a.MAX_TEXTURE_SIZE)?4096:2048;for(d=0;void 0>d;d++)c[d].textureSize=a;this._tarURI=b["src"+a];this._tarSize=parseInt(b["size"+a]);this._init()}WebGLScene.prototype=Object.create(Scene.prototype);WebGLScene.prototype.constructor=WebGLScene;WebGLScene.prototype._layers=null;WebGLScene.prototype._vertexShader=null;
WebGLScene.prototype._fragmentShader=null;WebGLScene.prototype._program=null;WebGLScene.prototype._positionLocationAttr=null;WebGLScene.prototype._texCoordLocationAttr=null;WebGLScene.prototype._resolutionLocationAttr=null;WebGLScene.prototype._imagesLoadHandlerBound=null;SimpleScene.prototype._numImagesLoaded=0;SimpleScene.prototype._numImages=0;SimpleScene.prototype._context=0;SimpleScene.prototype._s3tcExtension=null;SimpleScene.prototype._imagesFileBySrc=null;SimpleScene.prototype._tarURI=null;
SimpleScene.prototype._tarSize=null;SimpleScene.prototype._tarLoader=null;SimpleScene.prototype._tarLoadAsyncID=0;SimpleScene.prototype._tarProgressHandlerBound=null;SimpleScene.prototype._tarErrorHandlerBound=null;SimpleScene.prototype._tarAbortHandlerBound=null;SimpleScene.prototype._tarLoadHandlerBound=null;WebGLScene.prototype.updateSize=function(a,b){this._context.viewport(0,0,a,b);this._context.uniform2f(this._resolutionLocationAttr,a,b)};
WebGLScene.prototype._tarProgressHandler=function(a){var b=a.total;a.lengthComputable||(b=isNaN(this._tarSize)?0:this._tarSize);this._dispatchProgressEvent(a.loaded,b)};WebGLScene.prototype._tarErrorHandler=function(){this._dispatchErrorEvent()};WebGLScene.prototype._tarAbortHandler=function(){this._dispatchAbortEvent()};WebGLScene.prototype._tarLoadHandler=function(a){this._tarLoadAsyncID=setTimeout(this._tarLoadAsync.bind(this),0)};
WebGLScene.prototype._tarLoadAsync=function(){var a=new TarReader;a.readChunk(this._tarLoader.response);this._readTar(a)};
WebGLScene.prototype._readTar=function(a){var b,c,d=[],e=[],f,g;f=0;for(g=a.files.length;f<g;f++)switch(b=a.files[f],c=null,this._getFilenameExtension(b.name).toLowerCase()){case "dds":this._readDDS(b);break;case "json":this._readJSON(b);break;case "png":c=c?c:"image/png";case "jpg":case "jpeg":c=c?c:"image/jpeg";d.push(c);this._numImages=e.push(b);break;default:console.log('Tar: Unknown file "'+b.name+'"')}if(0<this._numImages)for(f=this._numImagesLoaded=0,g=e.length;f<g;f++)this._readImage(e[f],
d[f]);else this._loaded=!0,this._dispatchLoadEvent()};WebGLScene.prototype._findLayerByName=function(a){for(var b=0,c=this._layers.length;b<c;b++)if(this._layers[b].name==a)return this._layers[b];return null};WebGLScene.prototype._setTexture=function(a,b){var c=a.match(/\d+$/),d=parseInt(c,10);isNaN(d)&&(c="",d=0);var e,f;(e=a.substr(0,a.length-c.length))&&(f=this._findLayerByName(e))&&(f.textures[d]=b)};
WebGLScene.prototype._readDDS=function(a){var b,c=new DDSReader;try{c.read(a.data)}catch(d){return}0<c.mipmaps.length&&c.mipmaps[0]&&(b=this._createTexture(c.mipmaps[0]))&&this._setTexture(this._getFilename(a.name),b)};WebGLScene.prototype._readJSON=function(a){for(var b=a.data.byteLength,c="",d=new Uint8Array(a.data),e,f=0;f<b;++f)c+=String.fromCharCode(d[f]);try{d=JSON.parse(c)}catch(g){}d&&(e=this._findLayerByName(this._getFilename(a.name)))&&(e.frames=d)};
WebGLScene.prototype._readImage=function(a,b){this._imagesFileBySrc||(this._imagesFileBySrc={});var c=new Blob([new Uint8Array(a.data)],{type:b}),d=document.createElement("img");d.addEventListener("load",this._imagesLoadHandlerBound,!1);c=URL.createObjectURL(c);this._imagesFileBySrc[c]=a;d.src=c};
WebGLScene.prototype._imagesLoadHandler=function(a){a=a.currentTarget;a.removeEventListener("load",this._imagesLoadHandlerBound,!1);var b=a.src;window.URL.revokeObjectURL(b);var b=this._imagesFileBySrc[b],c;0<a.naturalWidth&&0<a.naturalHeight&&(c=this._createTexture(a))&&this._setTexture(this._getFilename(b.name),c);++this._numImagesLoaded>=this._numImages&&(this._loaded=!0,this._imagesFileBySrc=null,this._dispatchLoadEvent())};
WebGLScene.prototype._getFilenameExtension=function(a){var b=a.lastIndexOf(".");return 0>b?null:a.substr(b+1)};WebGLScene.prototype._getFilename=function(a){var b=a.lastIndexOf(".");return 0>b?a:a.substr(0,b)};WebGLScene.VERTEX_SHADER_SRC="attribute vec2 a_position;\nattribute vec2 a_texCoord;\nuniform vec2 u_resolution;\nvarying vec2 v_texCoord;\n\nvoid main() {\n\t// convert the rectangle from pixels to 0.0 to 1.0\n\tvec2 zeroToOne = a_position / u_resolution;\n\t// convert from 0->1 to 0->2\n\tvec2 zeroToTwo = zeroToOne * 2.0;\n\t// convert from 0->2 to -1->+1 (clipSpace)\n\tvec2 clipSpace = zeroToTwo - 1.0;\n\tgl_Position = vec4(clipSpace * vec2(1, -1), 0, 1);\n\t// pass the texCoord to the fragment shader\n\t// The GPU will interpolate this value between points.\n\tv_texCoord = a_texCoord;\n}";
WebGLScene.FRAGMENT_SHADER_SRC="precision mediump float;\nuniform sampler2D u_canvas1;\nuniform float u_contrast;\nuniform float u_brightness;\nvarying vec2 v_texCoord;\n\nvoid main() {\n\tvec4 fragColor = texture2D(u_canvas1, v_texCoord);\n\tvec3 color = fragColor.rgb;\n\t//Set Brightness\n\tfloat bFactor = 1.0 - abs(u_brightness) * 0.5;\n\tcolor *= bFactor;\n\tcolor += u_brightness > 0. ? 1.0 - bFactor: 0.0;\n\t//Set Contrast\n\tcolor = (color - 0.5) * (1.0 + u_contrast) + 0.5;\n\tgl_FragColor = vec4(color, fragColor.a);\n}";
WebGLScene.prototype._init=function(){this._vertexShader=this._context.createShader(this._context.VERTEX_SHADER);this._context.shaderSource(this._vertexShader,WebGLScene.VERTEX_SHADER_SRC);this._context.compileShader(this._vertexShader);this._fragmentShader=this._context.createShader(this._context.FRAGMENT_SHADER);this._context.shaderSource(this._fragmentShader,WebGLScene.FRAGMENT_SHADER_SRC);this._context.compileShader(this._fragmentShader);this._program=this._context.createProgram();this._context.attachShader(this._program,
this._vertexShader);this._context.attachShader(this._program,this._fragmentShader);this._context.linkProgram(this._program);this._context.useProgram(this._program);this._context.enable(this._context.BLEND);this._positionLocationAttr=this._context.getAttribLocation(this._program,"a_position");this._texCoordLocationAttr=this._context.getAttribLocation(this._program,"a_texCoord");this._resolutionLocationAttr=this._context.getUniformLocation(this._program,"u_resolution");var a=this._context.getUniformLocation(this._program,
"u_canvas1");this._context.uniform1i(a,0);this._context.activeTexture(this._context.TEXTURE0)};
WebGLScene.prototype._createTexture=function(a){var b=this._context.createTexture(),c=this._context.TEXTURE_2D;this._context.bindTexture(c,b);if(a instanceof ImageData||a instanceof HTMLImageElement||a instanceof HTMLCanvasElement||a instanceof HTMLVideoElement)this._context.texImage2D(c,0,this._context.RGBA,this._context.RGBA,this._context.UNSIGNED_BYTE,a);else if(a instanceof DDSMipmapLevel){var d;switch(a.format){case DDSReader.RGB_S3TC_DXT1:d=this._s3tcExtension.COMPRESSED_RGB_S3TC_DXT1_EXT;break;
case DDSReader.RGBA_S3TC_DXT1:d=this._s3tcExtension.COMPRESSED_RGBA_S3TC_DXT1_EXT;break;case DDSReader.RGBA_S3TC_DXT3:d=this._s3tcExtension.COMPRESSED_RGBA_S3TC_DXT3_EXT;break;case DDSReader.RGBA_S3TC_DXT5:d=this._s3tcExtension.COMPRESSED_RGBA_S3TC_DXT5_EXT;break;default:throw new TypeError("Unsupported format");}this._context.compressedTexImage2D(c,0,d,a.width,a.height,0,new Uint8Array(a.data,0,a.data.byteLength))}else throw new TypeError("Unsupported data");this._context.texParameteri(c,this._context.TEXTURE_MAG_FILTER,
this._context.LINEAR);this._context.texParameteri(c,this._context.TEXTURE_MIN_FILTER,this._context.LINEAR);this._context.texParameteri(c,this._context.TEXTURE_WRAP_S,this._context.CLAMP_TO_EDGE);this._context.texParameteri(c,this._context.TEXTURE_WRAP_T,this._context.CLAMP_TO_EDGE);return b};
WebGLScene.prototype.load=function(){this._tarLoader=new XMLHttpRequest;this._tarLoader.addEventListener("progress",this._tarProgressHandlerBound);this._tarLoader.addEventListener("error",this._tarErrorHandlerBound);this._tarLoader.addEventListener("abort",this._tarAbortHandlerBound);this._tarLoader.addEventListener("load",this._tarLoadHandlerBound);this._tarLoader.open("GET",this._tarURI,!0);this._tarLoader.responseType="arraybuffer";this._tarLoader.send(null)};
WebGLScene.prototype.draw=function(a,b){if(this._loaded){var c,d,e=this._layers.length,f,g=[],h,k=[],l=Array(e),m=Array(e),n=this._element.width,p=this._element.height;for(c=0;c<e;c++){d=this._layers[c];f=d.getTexCoords(a,b);h=d.getRectCoords(a,b,n,p);if(f.length!=h.length)throw Error("Num vertices and num UV don't match!");l[c]=f.length/2;g=g.concat(f);k=k.concat(h);m[c]=d.getTexture(a,b)}this._context.bindBuffer(this._context.ARRAY_BUFFER,this._context.createBuffer());this._context.bufferData(this._context.ARRAY_BUFFER,
new Float32Array(k),this._context.STATIC_DRAW);this._context.enableVertexAttribArray(this._positionLocationAttr);this._context.vertexAttribPointer(this._positionLocationAttr,2,this._context.FLOAT,!1,0,0);this._context.bindBuffer(this._context.ARRAY_BUFFER,this._context.createBuffer());this._context.bufferData(this._context.ARRAY_BUFFER,new Float32Array(g),this._context.STATIC_DRAW);this._context.enableVertexAttribArray(this._texCoordLocationAttr);this._context.vertexAttribPointer(this._texCoordLocationAttr,
2,this._context.FLOAT,!1,0,0);for(c=f=0;c<e;c++)d=this._layers[c],g=l[c],d instanceof BackgroundLayer?(h=d.getColor(a,b),this._context.clearColor(h.r/255,h.g/255,h.b/255,1),this._context.clear(this._context.COLOR_BUFFER_BIT),this._context.uniform1f(this._context.getUniformLocation(this._program,"u_contrast"),h.contrast/100),this._context.uniform1f(this._context.getUniformLocation(this._program,"u_brightness"),h.brightness/100)):(this._context.uniform1f(this._context.getUniformLocation(this._program,
"u_contrast"),0),this._context.uniform1f(this._context.getUniformLocation(this._program,"u_brightness"),0)),m[c]&&(d.blending.separate?this._context.blendFuncSeparate(d.blending.srcRGB,d.blending.dstRGB,d.blending.srcAlpha,d.blending.dstAlpha):this._context.blendFunc(d.blending.sFactor,d.blending.dFactor),this._context.bindTexture(this._context.TEXTURE_2D,m[c]),this._context.drawArrays(this._context.TRIANGLES,f,g),f+=g)}};
WebGLScene.test=function(a,b){var c,d;b=b||{alpha:!1};a=a.cloneNode(!1);try{c=a instanceof HTMLCanvasElement}catch(e){return!1}if(!c)return!1;try{d=a.getContext("webgl",b)||a.getContext("experimental-webgl",b)}catch(f){return!1}return d&&(d.getExtension("WEBGL_compressed_texture_s3tc")||d.getExtension("MOZ_WEBGL_compressed_texture_s3tc")||d.getExtension("WEBKIT_WEBGL_compressed_texture_s3tc"))&&2048<=d.getParameter(d.MAX_TEXTURE_SIZE)?!0:!1};
WebGLScene.prototype.clear=function(){Scene.prototype.clear.call(this);clearTimeout(this._tarLoadAsyncID);this._tarLoader&&(this._tarLoader.removeEventListener("progress",this._tarProgressHandlerBound),this._tarLoader.removeEventListener("error",this._tarErrorHandlerBound),this._tarLoader.removeEventListener("abort",this._tarAbortHandlerBound),this._tarLoader.removeEventListener("load",this._tarLoadHandlerBound),this._tarLoader.abort());for(var a in this._imagesFileBySrc)this._imagesFileBySrc.hasOwnProperty(a)&&
this._imagesFileBySrc[a]instanceof Image&&(this._imagesFileBySrc[a].removeEventListener("load",this._imagesLoadHandlerBound,!1),this._imagesFileBySrc[a]=null);a=this._context.getParameter(this._context.MAX_TEXTURE_IMAGE_UNITS);for(var b=0;b<a;++b)this._context.activeTexture(this._context.TEXTURE0+b),this._context.bindTexture(this._context.TEXTURE_2D,null),this._context.bindTexture(this._context.TEXTURE_CUBE_MAP,null);this._context.bindBuffer(this._context.ARRAY_BUFFER,null);this._context.bindBuffer(this._context.ELEMENT_ARRAY_BUFFER,
null);this._context.bindRenderbuffer(this._context.RENDERBUFFER,null);this._context.bindFramebuffer(this._context.FRAMEBUFFER,null);return!0};var DEBUG=!1;new ThreeJuly(document.documentElement);//# sourceMappingURL=scripts.js.map
